name: boring_flutter_project
description: A new Flutter project.

dependencies:
  url_launcher: ^3.0.3

  http: ^0.11.3+17

  intl: ^0.15.7

  meta: ^1.0.4

  rxdart: ^0.18.1

  font_awesome_flutter: ^8.0.1

  built_collection: '>=2.0.0 <4.0.0'
  built_value: '>=5.5.5 <7.0.0'

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^0.9.0
  built_value_generator: ^6.0.0

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
